In [57]:
import pandas as pd
import numpy as np


In [54]:
df1=pd.DataFrame({'A':'1,2,3,4,5'.split(','),
      'B':'2,34,5,67,4'.split(','),
            'C':'2,34,56566,67,4'.split(','),
            'D':'2,3477,5,67,4'.split(',')
      
     
     })

In [55]:
df2=pd.DataFrame({'X':'1,2,3,4,5'.split(','),
      'Y':'2,34,5,67,4'.split(','),
            'Z':'2,34,56566,67,4'.split(','),
            'A':'2,3477,5,67,4'.split(',')
      
     
     })

In [56]:
df2

X   Y      Z     A
0  1   2      2     2
1  2  34     34  3477
2  3   5  56566     5
3  4  67     67    67
4  5   4      4     4

In [45]:
pd.merge(df1,df2,how='right')

A    B    C     D  X   Y      Z
0     2   34   34  3477  1   2      2
1  3477  NaN  NaN   NaN  2  34     34
2     5    4    4     4  3   5  56566
3    67  NaN  NaN   NaN  4  67     67
4     4   67   67    67  5   4      4

In [30]:
df1.join(df2)

B      C     D    X    Y      Z
A                                  
1   2      2     2  NaN  NaN    NaN
2  34     34  3477    1    2      2
3   5  56566     5  NaN  NaN    NaN
4  67     67    67    5    4      4
5   4      4     4    3    5  56566

In [27]:
df2.dtypes

X    object
Y    object
Z    object
A    object
dtype: object

In [26]:
df2.index.dtype

dtype('int64')

In [28]:
df2.set_index('A',inplace=True)

In [36]:
df1.set_index('A',inplace=True)


In [41]:
df1

B      C     D
A                 
1   2      2     2
2  34     34  3477
3   5  56566     5
4  67     67    67
5   4      4     4

In [42]:
df2

X   Y      Z
A                 
2     1   2      2
3477  2  34     34
5     3   5  56566
67    4  67     67
4     5   4      4

In [46]:
df1

A   B      C     D
0  1   2      2     2
1  2  34     34  3477
2  3   5  56566     5
3  4  67     67    67
4  5   4      4     4

In [49]:
a=df1.describe()

In [48]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A       5 non-null      object
 1   B       5 non-null      object
 2   C       5 non-null      object
 3   D       5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes


In [50]:
a

A  B  C  D
count   5  5  5  5
unique  5  5  5  5
top     2  2  2  2
freq    1  1  1  1

In [52]:
a['A']['top']

'2'

In [53]:
a.describe()

A  B  C  D
count   4  4  4  4
unique  3  3  3  3
top     5  5  5  5
freq    2  2  2  2

In [58]:
a=np.array([1,2,3,4,5,])

In [59]:
b=a

In [60]:
a

array([1, 2, 3, 4, 5])

In [61]:
b

array([1, 2, 3, 4, 5])

In [64]:
b[0]=21

In [65]:
b

array([21,  2,  3,  4,  5])

In [66]:
a

array([21,  2,  3,  4,  5])

In [67]:
a

array([21,  2,  3,  4,  5])

In [68]:
c=np.copy(a)

In [69]:
a

array([21,  2,  3,  4,  5])

In [70]:
c

array([21,  2,  3,  4,  5])

In [72]:
c[0]=22233

In [73]:
c

array([22233,     2,     3,     4,     5])

In [74]:
a

array([21,  2,  3,  4,  5])

In [75]:
a

array([21,  2,  3,  4,  5])

In [76]:
b

array([21,  2,  3,  4,  5])

In [77]:
c

array([22233,     2,     3,     4,     5])

In [82]:
a=np.arange(20)

In [83]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
a=np.fromfunction(lambda x,y :x+y,(4,4),dtype=int)
a

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [95]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [141]:
b=np.fromstring('2,3,4,5',sep=(','),dtype=int)
b

array([2, 3, 4, 5])

In [99]:
b

array([2, 3, 4, 5])

In [125]:
x=np.arange(2.44,390.66,200)
x

array([  2.44, 202.44])

In [112]:
a=np.arange(10.5,dtype=int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
y= list(range(10))

In [122]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [123]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [143]:
a=np.linspace(1,10,4,dtype=int)
a

array([ 1,  4,  7, 10])

In [137]:
a

array([ 1.,  4.,  7., 10.])

In [138]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [157]:
a=np.fromfunction(lambda x,y:y+1,(10,10),dtype=int)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [158]:
pow(a,2)

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]], dtype=int32)

In [159]:
a-2

array([[-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8]])

# Matrix Multiplication

In [162]:
a@a

array([[ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550],
       [ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550]])

In [161]:
a*a

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [147]:
b=a

In [151]:
b=np.copy(a)

In [154]:
b[3]=567

In [155]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [326, 326, 326, 326, 326, 326, 326, 326, 326, 326],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [156]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [567, 567, 567, 567, 567, 567, 567, 567, 567, 567],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [163]:
a.shape

(10, 10)

In [164]:
a.size

100

In [165]:
a.ndim

2

In [166]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [167]:
a.shape

(10, 10)

In [171]:
a.reshape(4,5,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [172]:
df=pd.read_csv('FoodData')

In [174]:
del df['Unnamed: 0']

In [179]:
a=df.groupby('item_name')

In [180]:
a

In [220]:
df.groupby('item_name').sales_amount.sum().sort_values(ascending=False)

item_name
Chicken Bowl                             8044.63
Chicken Burrito                          6387.06
Steak Burrito                            4236.13
Steak Bowl                               2479.81
Chips and Guacamole                      2475.62
Chicken Salad Bowl                       1506.25
Chicken Soft Tacos                       1199.01
Chips and Fresh Tomato Salsa             1033.96
Veggie Burrito                           1002.27
Veggie Bowl                               901.95
Barbacoa Burrito                          894.75
Carnitas Bowl                             830.71
Barbacoa Bowl                             672.36
Bottled Water                             649.18
Carnitas Burrito                          616.33
Canned Soft Drink                         603.75
Chips                                     580.34
Steak Soft Tacos                          554.55
Chicken Crispy Tacos                      524.11
Steak Salad Bowl                          391.15
Carnitas S

In [195]:
df

order_id  quantity                              item_name  item_price  \
0            1         1           Chips and Fresh Tomato Salsa        2.39   
1            1         1                                   Izze        3.39   
2            1         1                       Nantucket Nectar        3.39   
3            1         1  Chips and Tomatillo-Green Chili Salsa        2.39   
4            2         2                           Chicken Bowl       16.98   
...        ...       ...                                    ...         ...   
4617      1833         1                          Steak Burrito       11.75   
4618      1833         1                          Steak Burrito       11.75   
4619      1834         1                     Chicken Salad Bowl       11.25   
4620      1834         1                     Chicken Salad Bowl        8.75   
4621      1834         1                     Chicken Salad Bowl        8.75   

      sales_amount                                 choice_description  \
0             2.39                                                NaN   
1             3.39                                       [Clementine]   
2             3.39                                            [Apple]   
3             2.39                                                NaN   
4            33.96  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...   
...            ...                                                ...   
4617         11.75  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...   
4618         11.75  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...   
4619         11.25  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   
4620          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...   
4621          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   

     sales_priority  percentage_revenue  
0               LoW            0.000061  
1               LoW            0.000086  
2               LoW            0.000086  
3               LoW            0.000061  
4              HiGh            0.000866  
...             ...                 ...  
4617         Medium            0.000299  
4618         Medium            0.000299  
4619         Medium            0.000287  
4620            LoW            0.000223  
4621            LoW            0.000223  

[4622 rows x 8 columns]

In [196]:
df.isnull()

order_id  quantity  item_name  item_price  sales_amount  \
0        False     False      False       False         False   
1        False     False      False       False         False   
2        False     False      False       False         False   
3        False     False      False       False         False   
4        False     False      False       False         False   
...        ...       ...        ...         ...           ...   
4617     False     False      False       False         False   
4618     False     False      False       False         False   
4619     False     False      False       False         False   
4620     False     False      False       False         False   
4621     False     False      False       False         False   

      choice_description  sales_priority  percentage_revenue  
0                   True           False               False  
1                  False           False               False  
2                  False           False               False  
3                   True           False               False  
4                  False           False               False  
...                  ...             ...                 ...  
4617               False           False               False  
4618               False           False               False  
4619               False           False               False  
4620               False           False               False  
4621               False           False               False  

[4622 rows x 8 columns]

In [198]:
df['sales_amount'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
4617    False
4618    False
4619    False
4620    False
4621    False
Name: sales_amount, Length: 4622, dtype: bool

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   order_id            4622 non-null   int64  
 1   quantity            4622 non-null   int64  
 2   item_name           4622 non-null   object 
 3   item_price          4622 non-null   float64
 4   sales_amount        4622 non-null   float64
 5   choice_description  3376 non-null   object 
 6   sales_priority      4622 non-null   object 
 7   percentage_revenue  4622 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 289.0+ KB


In [200]:
df['item_name']

1395    Veggie Soft Tacos
1699    Veggie Soft Tacos
2851    Veggie Soft Tacos
781     Veggie Soft Tacos
2384    Veggie Soft Tacos
              ...        
2713    6 Pack Soft Drink
1860    6 Pack Soft Drink
1849    6 Pack Soft Drink
341     6 Pack Soft Drink
3389    6 Pack Soft Drink
Name: item_name, Length: 4622, dtype: object

In [211]:
df.describe()

order_id     quantity   item_price  sales_amount  percentage_revenue
count  4622.000000  4622.000000  4622.000000   4622.000000         4622.000000
mean    927.254868     1.075725     7.464336      8.489186            0.000216
std     528.890796     0.410186     4.245557     12.632060            0.000322
min       1.000000     1.000000     1.090000      1.090000            0.000028
25%     477.250000     1.000000     3.390000      3.990000            0.000102
50%     926.000000     1.000000     8.750000      8.750000            0.000223
75%    1393.000000     1.000000     9.250000     10.980000            0.000280
max    1834.000000    15.000000    44.250000    663.750000            0.016916

In [260]:
df[df['sales_amount']>140].head(5)

order_id  quantity                     item_name  item_price  \
3598      1443        15  Chips and Fresh Tomato Salsa       44.25   
4152      1660        10                 Bottled Water       15.00   

      sales_amount choice_description sales_priority  percentage_revenue  
3598        663.75                NaN           HiGh            0.016916  
4152        150.00                NaN           HiGh            0.003823

In [271]:
df[df['choice_description']=='No Description']

order_id  quantity                              item_name  item_price  \
0            1         1           Chips and Fresh Tomato Salsa        2.39   
3            1         1  Chips and Tomatillo-Green Chili Salsa        2.39   
6            3         1                          Side of Chips        1.69   
10           5         1                    Chips and Guacamole        4.45   
14           7         1                    Chips and Guacamole        4.45   
...        ...       ...                                    ...         ...   
4600      1827         1                    Chips and Guacamole        4.45   
4605      1828         1                    Chips and Guacamole        4.45   
4613      1831         1                                  Chips        2.15   
4614      1831         1                          Bottled Water        1.50   
4616      1832         1                    Chips and Guacamole        4.45   

      sales_amount choice_description sales_priority  percentage_revenue  
0             2.39     No Description            LoW            0.000061  
3             2.39     No Description            LoW            0.000061  
6             1.69     No Description            LoW            0.000043  
10            4.45     No Description            LoW            0.000113  
14            4.45     No Description            LoW            0.000113  
...            ...                ...            ...                 ...  
4600          4.45     No Description            LoW            0.000113  
4605          4.45     No Description            LoW            0.000113  
4613          2.15     No Description            LoW            0.000055  
4614          1.50     No Description            LoW            0.000038  
4616          4.45     No Description            LoW            0.000113  

[1246 rows x 8 columns]

In [281]:
df

order_id  quantity                              item_name  item_price  \
0            1         1           Chips and Fresh Tomato Salsa        2.39   
1            1         1                                   Izze        3.39   
2            1         1                       Nantucket Nectar        3.39   
3            1         1  Chips and Tomatillo-Green Chili Salsa        2.39   
4            2         2                           Chicken Bowl       16.98   
...        ...       ...                                    ...         ...   
4617      1833         1                          Steak Burrito       11.75   
4618      1833         1                          Steak Burrito       11.75   
4619      1834         1                     Chicken Salad Bowl       11.25   
4620      1834         1                     Chicken Salad Bowl        8.75   
4621      1834         1                     Chicken Salad Bowl        8.75   

      sales_amount                                 choice_description  \
0             2.39                                                 ND   
1             3.39                                       [Clementine]   
2             3.39                                            [Apple]   
3             2.39                                                 ND   
4            33.96  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...   
...            ...                                                ...   
4617         11.75  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...   
4618         11.75  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...   
4619         11.25  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   
4620          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...   
4621          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   

     sales_priority  percentage_revenue  
0               LoW            0.000061  
1               LoW            0.000086  
2               LoW            0.000086  
3               LoW            0.000061  
4              HiGh            0.000866  
...             ...                 ...  
4617         Medium            0.000299  
4618         Medium            0.000299  
4619         Medium            0.000287  
4620            LoW            0.000223  
4621            LoW            0.000223  

[4622 rows x 8 columns]

In [273]:
df['choice_description'].replace('No Description', 'ND', inplace=True)

In [284]:
df[df['choice_description']=='ND'].value_counts().sum()

1246

In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   order_id            4622 non-null   int64  
 1   quantity            4622 non-null   int64  
 2   item_name           4622 non-null   object 
 3   item_price          4622 non-null   float64
 4   sales_amount        4622 non-null   float64
 5   choice_description  4622 non-null   object 
 6   sales_priority      4622 non-null   object 
 7   percentage_revenue  4622 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 289.0+ KB


In [268]:
df

order_id  quantity                              item_name  item_price  \
0            1         1           Chips and Fresh Tomato Salsa        2.39   
1            1         1                                   Izze        3.39   
2            1         1                       Nantucket Nectar        3.39   
3            1         1  Chips and Tomatillo-Green Chili Salsa        2.39   
4            2         2                           Chicken Bowl       16.98   
...        ...       ...                                    ...         ...   
4617      1833         1                          Steak Burrito       11.75   
4618      1833         1                          Steak Burrito       11.75   
4619      1834         1                     Chicken Salad Bowl       11.25   
4620      1834         1                     Chicken Salad Bowl        8.75   
4621      1834         1                     Chicken Salad Bowl        8.75   

      sales_amount                                 choice_description  \
0             2.39                                     No Description   
1             3.39                                       [Clementine]   
2             3.39                                            [Apple]   
3             2.39                                     No Description   
4            33.96  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...   
...            ...                                                ...   
4617         11.75  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...   
4618         11.75  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...   
4619         11.25  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   
4620          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...   
4621          8.75  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   

     sales_priority  percentage_revenue  
0               LoW            0.000061  
1               LoW            0.000086  
2               LoW            0.000086  
3               LoW            0.000061  
4              HiGh            0.000866  
...             ...                 ...  
4617         Medium            0.000299  
4618         Medium            0.000299  
4619         Medium            0.000287  
4620            LoW            0.000223  
4621            LoW            0.000223  

[4622 rows x 8 columns]

In [298]:
df[df['item_name']=='Chicken Salad Bowl']['sales_amount'].mean()

13.693181818181818

In [286]:
df.to_csv('FoodData.csv')

In [297]:
df.groupby('item_name').sales_amount.sum().sort_values(ascending=False).to_frame().head(10)

sales_amount
item_name                                 
Chicken Bowl                       8044.63
Chicken Burrito                    6387.06
Steak Burrito                      4236.13
Steak Bowl                         2479.81
Chips and Guacamole                2475.62
Chicken Salad Bowl                 1506.25
Chicken Soft Tacos                 1199.01
Chips and Fresh Tomato Salsa       1033.96
Veggie Burrito                     1002.27
Veggie Bowl                         901.95